# Generated by Django 4.2 on 2024-06-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_mobile',
            old_name='Dateofbirth',
            new_name='DateofBirth',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='email_address',
            new_name='EmailAddress',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='Language_perfered',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='first_name',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='mobile_number',
            new_name='MobileNumber',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='ndis_number',
            new_name='NdisNumber',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='Refferal_code',
            new_name='RefferalCode',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='signing_as',
            new_name='Signing_as',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='user_id',
            new_name='UserId',
        ),
    ]
