# Generated by Django 4.2 on 2024-06-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0002_user_mobile_is_admin_alter_user_mobile_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mobile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
