# Generated by Django 4.2 on 2024-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0003_alter_user_mobile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='Language_perfered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_mobile',
            name='Refferal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
