# Generated by Django 4.2 on 2024-06-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0004_user_mobile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mobile',
            name='password',
            field=models.CharField(max_length=15, verbose_name='Password'),
        ),
    ]
