# Generated by Django 4.2 on 2024-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0004_user_mobile_language_perfered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='signing_as',
            field=models.CharField(choices=[('Self', 'Self'), ('Parent', 'Parent')], default='Self', max_length=6),
        ),
    ]
