# Generated by Django 4.2 on 2024-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0005_alter_user_mobile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='Created_At',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
