# Generated by Django 4.2 on 2024-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0006_user_mobile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mobile',
            name='Created_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
