# Generated by Django 4.2 on 2024-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0007_alter_user_mobile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_mobile',
            old_name='Language',
            new_name='communicationPreference',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='Created_At',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='DateofBirth',
            new_name='dateofBirth',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='EmailAddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='MobileNumber',
            new_name='mobileNumber',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='NdisNumber',
            new_name='ndisNumber',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='RefferalCode',
            new_name='refferalCode',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='Signing_as',
            new_name='signingAs',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='UserId',
            new_name='userId',
        ),
        # migrations.RemoveField(
        #     model_name='user_mobile',
        #     name='Language',
        # ),
        # migrations.RemoveField(
        #     model_name='user_mobile',
        #     name='LastName',
        # ),
        # migrations.AddField(
        #     model_name='user_mobile',
        #     name='firstName',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
