# Generated by Django 4.2 on 2024-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0009_alter_user_mobile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_handling',
            fields=[
                ('errorId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('status_Code', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
