# Generated by Django 4.2 on 2024-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0010_error_handling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error_handling',
            options={'managed': True, 'verbose_name': 'Error handling', 'verbose_name_plural': 'Error handling'},
        ),
        migrations.AddField(
            model_name='error_handling',
            name='default_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='error_handling',
            table='',
        ),
    ]
