# Generated by Django 4.2 on 2024-06-24 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0030_delete_client_details_delete_client_sub'),
        ('mobile_api_user', '0013_client_sub_client_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_details_view',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Client_provider.baseclass')),
                ('Client_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Number', models.PositiveIntegerField(blank=True, null=True)),
                ('Client_Sal', models.CharField(max_length=5)),
                ('Type', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('Add_Caretaker_Detail', models.ManyToManyField(to='mobile_api_user.client_sub')),
                ('Client_auth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client details',
                'verbose_name_plural': 'Client details',
                'db_table': '',
                'managed': True,
            },
            bases=('Client_provider.baseclass',),
        ),
        migrations.DeleteModel(
            name='Client_details',
        ),
    ]
