# Generated by Django 4.2 on 2024-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0014_client_details_view_delete_client_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_sub_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dateofbirth', models.DateTimeField()),
                ('Ndisnumber', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Client sub',
                'verbose_name_plural': 'Client sub',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Client_sub',
        ),
        migrations.AlterField(
            model_name='client_details_view',
            name='Add_Caretaker_Detail',
            field=models.ManyToManyField(to='mobile_api_user.client_sub_view'),
        ),
    ]
