# Generated by Django 4.2 on 2024-06-25 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0016_alter_client_details_view_add_caretaker_detail_and_more'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='client_sub_view',
            name='id',
        ),
        migrations.AddField(
            model_name='client_sub_view',
            name='clientSubId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client_details_view',
            name='Add_Caretaker_Detail',
            field=models.ManyToManyField(to='mobile_api_user.client_sub_view'),
        )
        # migrations.AlterField(
        #     model_name='client_details_view',
        #     name='Client_auth',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
