# Generated by Django 4.2 on 2024-06-25 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0017_remove_client_sub_view_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details_view',
            name='Client_auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
