# Generated by Django 4.2 on 2024-06-25 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0018_alter_client_details_view_client_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details_view',
            name='Client_auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client_sub_view',
            name='clientSubId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
