# Generated by Django 4.2 on 2024-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0020_alter_client_sub_view_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_sub_view',
            name='Ndisnumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
