# Generated by Django 4.2 on 2024-06-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0021_alter_client_sub_view_ndisnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_details_view',
            options={'managed': True, 'verbose_name': 'User Profiles', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='client_details_view',
            name='Client_Number',
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
