# Generated by Django 4.2 on 2024-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0022_alter_client_details_view_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_details_view',
            name='Client_Sal',
        ),
        migrations.AddField(
            model_name='user_mobile',
            name='Client_Sal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
