# Generated by Django 4.2 on 2024-06-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0025_alter_user_mobile_client_sal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_sub_view',
            old_name='Ndisnumber',
            new_name='insurance',
        ),
    ]
