# Generated by Django 4.2 on 2024-06-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0026_rename_ndisnumber_client_sub_view_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_sub_view',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='client_sub_view',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
