# Generated by Django 4.2 on 2024-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0027_rename_first_name_client_sub_view_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_details_view',
            old_name='Add_Caretaker_Detail',
            new_name='addChildren',
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_mobile',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
