# Generated by Django 4.2 on 2024-07-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0028_rename_add_caretaker_detail_client_details_view_addchildren_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_details_view',
            old_name='Type',
            new_name='type',
        ),
    ]
