# Generated by Django 4.2 on 2024-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0029_rename_type_client_details_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='firebaseKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
