# Generated by Django 4.2 on 2024-07-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0030_user_mobile_firebasekey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_sub_view',
            old_name='insurance',
            new_name='insuranceNumber',
        ),
        migrations.RenameField(
            model_name='user_mobile',
            old_name='ndisNumber',
            new_name='insuranceNumber',
        ),
    ]
