# Generated by Django 4.2 on 2024-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0031_rename_insurance_client_sub_view_insurancenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mobile',
            name='insuranceNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='user_mobile',
            constraint=models.UniqueConstraint(condition=models.Q(('insuranceNumber', None), _negated=True), fields=('insuranceNumber',), name='unique_insuranceNumber'),
        ),
    ]
