# Generated by Django 4.2 on 2024-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0032_alter_user_mobile_insurancenumber_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_mobile',
            name='unique_insuranceNumber',
        ),
        migrations.AlterField(
            model_name='client_sub_view',
            name='insuranceNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
