# Generated by Django 4.2 on 2024-07-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0033_remove_user_mobile_unique_insurancenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_mobile',
            name='insuranceType',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
