# Generated by Django 4.2 on 2024-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0034_user_mobile_insurancetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_sub_view',
            name='insuranceType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
