# Generated by Django 4.2 on 2024-08-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0036_rename_firebasekey_user_mobile_firebasekey'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='user_mobile',
            name='fireBaseKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
