# Generated by Django 4.2 on 2024-06-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='baseclass_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Client_provider.baseclass'),
            preserve_default=False,
        ),
    ]
