# Generated by Django 4.2 on 2024-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0002_provider_baseclass_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseclass',
            name='Alternative_mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseclass',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baseclass',
            name='PIN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baseclass',
            name='Permanent_Address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baseclass',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
