# Generated by Django 4.2 on 2024-06-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0003_alter_baseclass_alternative_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='Client_Number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
