# Generated by Django 4.2 on 2024-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0004_alter_client_details_client_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='multi_location',
        ),
        migrations.AddField(
            model_name='provider',
            name='multi_location',
            field=models.ManyToManyField(to='Client_provider.location'),
        ),
    ]
