# Generated by Django 4.2 on 2024-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0006_therapist_multi_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Therapist_add',
            field=models.ManyToManyField(to='Client_provider.therapist'),
        ),
    ]
