# Generated by Django 4.2 on 2024-06-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0007_service_therapist_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='session_type',
        ),
    ]
