# Generated by Django 4.2 on 2024-06-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0008_remove_service_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='date_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Therapist_booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tharapist_Booked', models.BooleanField(default=False)),
                ('therapy_completed', models.BooleanField(default=False)),
                ('therapy_start_booked_time', models.DateTimeField(blank=True, null=True)),
                ('therapy_end_booked_time', models.DateTimeField(blank=True, null=True)),
                ('therapist_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client_provider.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.service')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist')),
            ],
        ),
    ]
