# Generated by Django 4.2 on 2024-06-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client_provider', '0009_therapist_date_field_therapist_booked_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_auth',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Location_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapy_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapy_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Provider_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usertype', models.CharField(choices=[('admin', 'Admin'), ('check', 'Check'), ('tech', 'Tech')], max_length=5)),
                ('Users', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='User_add',
            field=models.ManyToManyField(to='Client_provider.provider_employee'),
        ),
    ]
