# Generated by Django 4.2 on 2024-06-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0010_remove_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist_booked',
            options={'managed': True, 'verbose_name': 'Therapist Booked slot', 'verbose_name_plural': 'Therapist Booked slot'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='Location_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.location'),
        ),
    ]
