# Generated by Django 4.2 on 2024-06-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0011_alter_therapist_booked_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='street_name',
        ),
    ]
