# Generated by Django 4.2 on 2024-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0013_provider_email_provider_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='Therapist_added',
            field=models.ManyToManyField(to='Client_provider.therapist'),
        ),
    ]
