# Generated by Django 4.2 on 2024-06-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0014_provider_therapist_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='therapist_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Therapist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client_provider.therapist')),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client_provider.service')),
            ],
        ),
    ]
