# Generated by Django 4.2 on 2024-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0015_therapist_service'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='provider',
        #     name='Therapist_added',
        #     field=models.ManyToManyField(to='Client_provider.therapist_service'),
        # ),
    ]
