# Generated by Django 4.2 on 2024-06-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0017_alter_provider_therapist_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='Therapist_added',
        ),
    ]
