# Generated by Django 4.2 on 2024-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0018_remove_provider_therapist_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service_add',
        ),
        migrations.AddField(
            model_name='provider',
            name='therapist_service_map',
            field=models.ManyToManyField(to='Client_provider.therapist_service'),
        ),
    ]
