# Generated by Django 4.2 on 2024-06-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0019_remove_provider_service_add_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist_service',
            old_name='Therapist_id',
            new_name='Therapist_Name',
        ),
        migrations.RenameField(
            model_name='therapist_service',
            old_name='service_id',
            new_name='service_Name',
        ),
    ]
