# Generated by Django 4.2 on 2024-06-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0020_rename_therapist_id_therapist_service_therapist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Therapist_add',
        ),
    ]
