# Generated by Django 4.2 on 2024-06-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0021_remove_service_therapist_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='dva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
