# Generated by Django 4.2 on 2024-06-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0022_alter_therapist_dva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='dva',
            new_name='DVA',
        ),
    ]
