# Generated by Django 4.2 on 2024-06-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0023_rename_dva_provider_dva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='Type',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='therapist_service',
            unique_together={('Therapist_Name', 'service_Name')},
        ),
    ]
