# Generated by Django 4.2 on 2024-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0026_rename_multi_location_provider_provider_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider_employee',
            name='Users',
        ),
        migrations.AddField(
            model_name='provider_employee',
            name='Users_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider_employee',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
