# Generated by Django 4.2 on 2024-06-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0027_remove_provider_employee_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_num',
            field=models.PositiveIntegerField(),
        ),
    ]
