# Generated by Django 4.2 on 2024-06-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0030_delete_client_details_delete_client_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='therapist_sal',
        ),
    ]
