# Generated by Django 4.2 on 2024-06-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0031_remove_therapist_therapist_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist_service',
            name='Therapist_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist'),
        ),
        migrations.AlterField(
            model_name='therapist_service',
            name='service_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.service'),
        ),
    ]
