# Generated by Django 4.2 on 2024-06-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0032_alter_therapist_service_therapist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='Provider_employers',
            new_name='ProviderEmployers',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='Provider_locations',
            new_name='ProviderLocations',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='age_group',
            new_name='ageGroup',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_id',
            new_name='providerId',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_name',
            new_name='providerName',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_num',
            new_name='providerNum',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='provider_type',
            new_name='providerType',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='therapist_service_map',
            new_name='therapistServicemap',
        ),
    ]
