# Generated by Django 4.2 on 2024-06-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0033_rename_provider_employers_provider_provideremployers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseclass',
            old_name='Additional_Info1',
            new_name='AdditionalInfo1',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='Additional_Info2',
            new_name='AdditionalInfo2',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='Additional_Info3',
            new_name='AdditionalInfo3',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='Additional_Info4',
            new_name='AdditionalInfo4',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='Alternative_mobile_number',
            new_name='AlternativeMobileNumber',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='Permanent_Address_1',
            new_name='PermanentAddress1',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='Permanent_Address_2',
            new_name='PermanentAddress2',
        ),
    ]
