# Generated by Django 4.2 on 2024-07-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0034_rename_additional_info1_baseclass_additionalinfo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist_unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('startime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Therapist_bookeds_slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist')),
            ],
        ),
    ]
