# Generated by Django 4.2 on 2024-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0035_therapist_unavailability_therapist_bookeds_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist_unavailability',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist_unavailability',
            name='updateAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
