# Generated by Django 4.2 on 2024-07-03 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0038_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='isConfirmed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='isconfimed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='therapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('isAvalable', models.BooleanField()),
                ('daySchedule', models.JSONField()),
                ('therapist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist')),
            ],
        ),
    ]
