# Generated by Django 4.2 on 2024-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0041_alter_therapist_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider_employee',
            options={'managed': True, 'verbose_name': 'Provider employee', 'verbose_name_plural': 'Provider employees'},
        ),
        migrations.AlterModelOptions(
            name='therapistavailability',
            options={'managed': True, 'verbose_name': 'therapist Availability', 'verbose_name_plural': 'therapist Availability'},
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='daySchedule',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='provider_employee',
            table='',
        ),
    ]
