# Generated by Django 4.2 on 2024-07-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0042_alter_provider_employee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistavailability',
            old_name='starttime',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='Provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.provider'),
        ),
    ]
