# Generated by Django 4.2 on 2024-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0043_rename_starttime_therapistavailability_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='childId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clientId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
