# Generated by Django 4.2 on 2024-07-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0044_alter_appointment_childid_alter_appointment_clientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='provider',
            new_name='providerId',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='serviceId',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='therapist',
            new_name='therapistId',
        ),
    ]
