# Generated by Django 4.2 on 2024-07-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0046_alter_appointment_therapytime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='TherapyTime_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='TherapyTime_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
