# Generated by Django 4.2 on 2024-07-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api_user', '0028_rename_add_caretaker_detail_client_details_view_addchildren_and_more'),
        ('Client_provider', '0048_appointment1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment1',
            name='childId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_api_user.client_sub_view'),
        ),
        migrations.AlterField(
            model_name='appointment1',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment1',
            name='providerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.provider'),
        ),
        migrations.AlterField(
            model_name='appointment1',
            name='serviceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.service'),
        ),
        migrations.AlterField(
            model_name='appointment1',
            name='therapistId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist'),
        ),
    ]
