# Generated by Django 4.2 on 2024-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0051_alter_appointment1_options_therapist_expirence'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistavailability',
            name='available_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('reschedule', 'reschedule')], default='waiting', max_length=10),
        ),
    ]
