# Generated by Django 4.2 on 2024-07-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0052_therapistavailability_available_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistavailability',
            name='daySchedule',
        ),
        migrations.AddField(
            model_name='appointment1',
            name='LocationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.location'),
        ),
    ]
