# Generated by Django 4.2 on 2024-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0053_remove_therapistavailability_dayschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistavailability',
            name='availableSlotsData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment1',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('reshudule', 'reshudule')], default='waiting', max_length=10),
        ),
    ]
