# Generated by Django 4.2 on 2024-07-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0055_rename_locationid_appointment1_locationdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment1',
            old_name='Locationdata',
            new_name='LocationData',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='childId',
            new_name='childid',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='clientdata',
            new_name='clientData',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='providerdata',
            new_name='providerData',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='servicedata',
            new_name='serviceData',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='therapistdata',
            new_name='therapistData',
        ),
    ]
