# Generated by Django 4.2 on 2024-07-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0056_rename_locationdata_appointment1_locationdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment1',
            old_name='childid',
            new_name='childId',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='LocationData',
            new_name='locationData',
        ),
    ]
