# Generated by Django 4.2 on 2024-07-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0057_rename_childid_appointment1_childid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseclass',
            old_name='AdditionalInfo1',
            new_name='additionalInfo1',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='AdditionalInfo2',
            new_name='additionalInfo2',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='AdditionalInfo3',
            new_name='additionalInfo3',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='AdditionalInfo4',
            new_name='additionalInfo4',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='AlternativeMobileNumber',
            new_name='alternativeMobileNumber',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='PermanentAddress1',
            new_name='permanentAddress1',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='PermanentAddress2',
            new_name='permanentAddress2',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='PIN',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='baseclass',
            old_name='State',
            new_name='state',
        ),
    ]
