# Generated by Django 4.2 on 2024-07-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0058_rename_additionalinfo1_baseclass_additionalinfo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='phoneNo',
        ),
    ]
