# Generated by Django 4.2 on 2024-07-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0059_remove_provider_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='expirence',
            new_name='experience',
        ),
    ]
