# Generated by Django 4.2 on 2024-07-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0060_rename_expirence_therapist_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='DVA',
            new_name='dva',
        ),
    ]
