# Generated by Django 4.2 on 2024-07-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0061_rename_dva_provider_dva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider_employee',
            old_name='Usertype',
            new_name='UserType',
        ),
        migrations.RenameField(
            model_name='provider_employee',
            old_name='Users_name',
            new_name='usersName',
        ),
        migrations.AlterModelTable(
            name='provider_employee',
            table=None,
        ),
    ]
