# Generated by Django 4.2 on 2024-07-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0062_rename_usertype_provider_employee_usertype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider_employee',
            old_name='UserType',
            new_name='userType',
        ),
    ]
