# Generated by Django 4.2 on 2024-08-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api_user', '0035_client_sub_view_insurancetype'),
        ('Client_provider', '0064_therapistpostreoccurappoinment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientPrebookAppointments',
            fields=[
                ('clientPreId', models.IntegerField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('endDate', models.DateField()),
                ('appointmentType', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily'), ('fortnight', 'Fortnightly'), ('alternativeType', 'Monthly')], default='weekly', max_length=15)),
                ('clientDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_api_user.client_details_view')),
                ('locationData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.location')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist')),
            ],
        ),
        migrations.DeleteModel(
            name='therapistPostReoccurAppoinment',
        ),
    ]
