# Generated by Django 4.2 on 2024-08-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client_provider', '0065_clientprebookappointments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprebookappointments',
            name='therapist',
        ),
        migrations.AddField(
            model_name='clientprebookappointments',
            name='providerDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.provider'),
        ),
        migrations.AddField(
            model_name='clientprebookappointments',
            name='therapistDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist'),
        ),
        migrations.AlterField(
            model_name='clientprebookappointments',
            name='clientDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprebookappointments',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprebookappointments',
            name='locationData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.location'),
        ),
        migrations.AlterField(
            model_name='clientprebookappointments',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
