# Generated by Django 4.2 on 2024-08-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0068_alter_appointment1_reapointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprebookappointments',
            name='clientPreId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
