# Generated by Django 4.2 on 2024-08-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0069_alter_clientprebookappointments_clientpreid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprebookappointments',
            options={'managed': True, 'verbose_name': 'client Prebook Appointment', 'verbose_name_plural': 'client Prebook Appointments'},
        ),
    ]
