# Generated by Django 4.2 on 2024-08-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0070_alter_clientprebookappointments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment1',
            name='IsTherapistChanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment1',
            name='therapistComments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
