# Generated by Django 4.2 on 2024-08-08 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_api_user', '0035_client_sub_view_insurancetype'),
        ('Client_provider', '0072_rename_istherapistchanged_appointment1_istherapistchanged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprebookappointments',
            options={'managed': True, 'verbose_name': 'Requested Appointment', 'verbose_name_plural': 'Requested Appointment'},
        ),
        migrations.RemoveField(
            model_name='appointment1',
            name='reapointment_id',
        ),
        migrations.AddField(
            model_name='appointment1',
            name='reoccurAppointment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReoccureAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField(blank=True, null=True)),
                ('TherapyTime_start', models.TimeField(blank=True, null=True)),
                ('TherapyTime_end', models.TimeField(blank=True, null=True)),
                ('Location_details', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Reoccur', 'Reoccur')], max_length=10)),
                ('isconfimed', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(blank=True, null=True)),
                ('isTherapistChanged', models.BooleanField(default=False)),
                ('therapistComments', models.TextField(blank=True, null=True)),
                ('childId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_api_user.client_sub_view')),
                ('clientData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locationData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.location')),
                ('providerData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.provider')),
                ('reoccurAppointmentValid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.clientprebookappointments')),
                ('serviceData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.service')),
                ('therapistData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client_provider.therapist')),
            ],
            options={
                'verbose_name': 'Apointments',
                'verbose_name_plural': 'Apointments',
                'managed': True,
            },
        ),
    ]
