# Generated by Django 4.2 on 2024-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0074_rename_reoccurappointmentvalid_reoccureappointments_reoccurappointmentdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reoccureappointments',
            options={'managed': True, 'verbose_name': 'reoccur Appointment', 'verbose_name_plural': 'reoccur Appointment'},
        ),
        migrations.AddField(
            model_name='clientprebookappointments',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reoccureappointments',
            name='status',
            field=models.CharField(choices=[('Reoccur', 'Reoccur'), ('waiting', 'waiting')], max_length=10),
        ),
    ]
