# Generated by Django 4.2 on 2024-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_provider', '0075_alter_reoccureappointments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprebookappointments',
            name='therapySlot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
